- name: Install Network Time Protocol(NTP) in Ubuntu
  apt:
    name:
      - chrony
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: "NTP service restart/enable"
  service:
    name: chrony
    state: restarted
    enabled: true

- name: Install OpenStack package (Client) in Ubuntu
  apt:
    name:
      - python3-openstackclient
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install SQL database for Ubuntu
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: "mysql service restart/enable"
  service:
    name: mysql
    state: restarted
    enabled: true

- name: Install Message Queue in Ubuntu
  apt:
    name:
      - rabbitmq-server
    state: latest
  when: ansible_distribution == "Ubuntu"

